### PR TITLE
Use `getComputedStyle()` util in `tabbable.ts`

### PR DESCRIPTION
**Pull request by LeaVerou**
Tiny PR, but didn't want to commit directly because I can't figure out where this code is used

### CODE REVIEW

**Comment by claviska** [comment]
@KonnorRogers wasn’t this for focus trapping? Can we remove it now?

**Comment by KonnorRogers** [comment]
@claviska correct. this should be removed iirc. was only used for focus trapping.

**Comment by LeaVerou** [comment]
You mean the entire file?

**Comment by KonnorRogers** [comment]
yup, pretty sure the whole file can be deleted!

**Comment by LeaVerou** [comment]
Okay, I will close this and do that then

**Pull request closed without merging**
