### PR TITLE
[DRAFT] Watch removal

### PR DESCRIPTION
**Pull request by claviska**
This PR removes the `@watch` decorator and alleviates any performance concerns in #206. It also sneaks in vertical orientation in `<wa-button-group>`.

I've noticed only three things that still need to be fixed, and they all seem related.

- [ ] Dropdown - opens and instantly closes
- [ ] Tooltip - opens and instantly closes
- [ ] Select - freezes the page due to recursion (probably from `open`)

### CODE REVIEW

**Comment by LeaVerou** [comment]
This PR seems to have a bunch of things that are completely unrelated to the title. Is that intentional?

**Comment by claviska** [comment]
whoops, yep, I should have split out vertical orientation in button group. Since it's here already, I've updated the description above.

The pattern page was a prettier error and then I also made some indentation fixes.

**Comment by claviska** [comment]
@KonnorRogers after digging, it looks like dropdown and tooltip are related to SSR. Disabling SSR makes them work. 🙈 

Select appears to be unrelated. Working on that one now.

**Comment by claviska** [comment]
Update: I've fixed the infinite loop in select and it _is_ also affected by SSR.

**Comment by claviska** [comment]
Thanks for the fixes, @KonnorRogers! I'm going to sort out the tests and get this one done tomorrow.

**Comment by claviska** [comment]
Ugh, abandoning this because tests are going crazy and it's become a rabbit hole. This was supposed to be a quick update, but it's not a priority for launch.

**Pull request closed without merging**
